name: ${pluginName}
version: ${version}
main: com.github.devotedmc.hiddenore.HiddenOre
author: Soerxpso
authors: [ProgrammerDan]
load: STARTUP
website: https://www.github.com/DevotedMC/HiddenOre
description: ${description}
api-version: ${api_version}
commands:
   hiddenore:
      description: HiddenOre allows the hiding of cool drops underground. This reloads the config.
      usage: |
       /hiddenore    -- reloads
       /hiddenore save -- forces save of tracking
       /hiddenore generate [num] -- drops all drops near the player issuing the command, use sparingly. 
      permission: hiddenore.adv
permissions:
    hiddenore.*:
      description: Gives access to all HiddenOre commands
      default: op
      children:
        hiddenore.adv: true
    hiddenore.adv:
      description: Allows access to  HiddenOre commands.
      default: op
